#!/usr/bin/env python3
"""Renders aggregated-results.json into a ranked Markdown report."""
import json
import os

BASE = os.path.dirname(os.path.abspath(__file__))

with open(os.path.join(BASE, 'aggregated-results.json')) as f:
    rows = json.load(f)

CATEGORY_LABELS = {
    'markdown_syntax': 'Markdown syntax',
    'spelling': 'Spelling',
    'grammar_style': 'Grammar/style',
    'broken_links': 'Broken links',
    'metadata': 'Metadata',
}

lines = []
lines.append('# Docs Review Report: Issue Ranking\n')
lines.append(
    'Generated by the local docs-review toolchain (markdownlint-cli2, cspell, '
    'Vale, lychee, and a custom front-matter checker) against every Markdown/MDX '
    'file under `docs/`. Files are ranked from **fewest to most issues**.\n'
)
lines.append(f"**Files reviewed:** {len(rows)}  \n**Total issues found:** {sum(r['total'] for r in rows)}\n")

lines.append('## Summary table\n')
header = ['Rank', 'File name', 'Path', 'Total issues'] + [CATEGORY_LABELS[c] for c in CATEGORY_LABELS]
lines.append('| ' + ' | '.join(header) + ' |')
lines.append('|' + '|'.join(['---'] * len(header)) + '|')
for r in rows:
    cat_cells = [str(r['by_category'].get(c, 0)) for c in CATEGORY_LABELS]
    lines.append(
        f"| {r['rank']} | {r['name']} | `{r['file']}` | {r['total']} | " + ' | '.join(cat_cells) + ' |'
    )

lines.append('\n## Detailed findings (files with issues, worst first)\n')
for r in sorted(rows, key=lambda r: -r['total']):
    if r['total'] == 0:
        continue
    lines.append(f"### {r['rank']}. `{r['file']}` — {r['total']} issue(s)\n")
    for cat, label in CATEGORY_LABELS.items():
        items = r['details'].get(cat, [])
        if not items:
            continue
        lines.append(f"**{label}** ({len(items)}):")
        for item in items[:15]:
            lines.append(f"- {item}")
        if len(items) > 15:
            lines.append(f"- ...and {len(items) - 15} more")
        lines.append('')

with open(os.path.join(BASE, 'report.md'), 'w') as f:
    f.write('\n'.join(lines))

print('Wrote report.md')
